import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';
import 'package:resepmakanan/cubit/resep_makanan_state.dart';
import 'package:resepmakanan/model/judul_makanan_model.dart';
import 'package:resepmakanan/request/resep_makanan_request.dart';
import 'package:meta/meta.dart';

class ResepCubit extends Cubit<ResepState> {
  ResepCubit() : super(ResepInitial());

  ResepMakananRequest resepMakananRequest = ResepMakananRequest();
  Autogenerated autogenerated = Autogenerated();

  getCurrentWeatherData() async {
    autogenerated = await resepMakananRequest.getCurrentWeather();
  }
}
