import 'package:flutter/cupertino.dart';
import 'package:resepmakanan/model/judul_makanan_model.dart';

@immutable
abstract class ResepState {}

class ResepInitial extends ResepState {}

class CurrentWeather extends ResepState {
  final Autogenerated data;
  CurrentWeather(this.data);
}
