class Autogenerated {
  String? method;
  String? message;
  bool? status;
  int? code;

  Autogenerated({this.method, this.message, this.status, this.code});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    method = json['method'];
    message = json['message'];
    status = json['status'];
    code = json['code'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['method'] = this.method;
    data['message'] = this.message;
    data['status'] = this.status;
    data['code'] = this.code;
    return data;
  }
}
