import 'package:resepmakanan/model/judul_makanan_model.dart';
import 'package:dio/dio.dart';

class ResepMakananRequest {
  Future<Autogenerated> getCurrentWeather() async {
    var response = await Dio()
        .get("https://masak-apa-tomorisakura.vercel.app/api/recipes");
    return Autogenerated.fromJson(response.data);
  }
}
